meta_product_name: ""
meta_title: ""
meta_description: " is the best product in the market"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
company_name: ""
company_website: ""
company_twitter: ""
setup_date: "Wed Nov 26 11:51:09 GMT 2025"

# Theme
LIGHT_THEME: "light"
DARK_THEME: "dark"
